---
    - name: Address Setup
      hosts: lab2
      connection: local
      gather_facts: no
      tasks:
        - name: Create Loopback
          with_items: "{{local_loopback}}"
          ios_interfaces:
            config:
              - name: "{{item.name}}"
                enabled: True
            state: merged
    
        - name: Set Loopback IP
          with_items: "{{local_loopback}}"
          ios_l3_interface:
            name: "{{item.name}}"
            ipv4: "{{item.ip_address}}"
    
        - name: Set Interface IPs
          with_items: "{{interfaces}}"
          ios_l3_interface:
            name: "{{item.name}}"
            ipv4: "{{item.ip_address}}"
    
        - name: No shut
          with_items: "{{interfaces}}"
          ios_interfaces:
            config:
              - name: "{{item.name}}"
                enabled: True
            state: merged

    - name: OSPF setup
      hosts: 10.10.21.211,10.10.21.212,10.10.21.213,10.10.21.221
      connection: local
      gather_facts: no
      tasks:
      - name: Enable OSPF
        ios_config:
            lines:          
              - network 100.100.100.0 0.0.0.255 area 0
              - auto-cost reference-bandwidth 1000
            parents: router ospf 1