---
    local_loopback:
      - name: Loopback1
        desc: Sample Ansible config
        ip_address: 6.6.6.6/32
    
    interfaces:
      - name: GigabitEthernet0/0
        ip_address: 120.120.120.2/30
      - name: GigabitEthernet0/1
        ip_address: 120.120.120.5/30