---
    local_loopback:
      - name: Loopback1
        desc: Sample Ansible config
        ip_address: 172.16.1.3/24
    
    interfaces:
      - name: GigabitEthernet0/1
        ip_address: 130.130.130.2/30
      - name: GigabitEthernet0/2
        ip_address: 130.130.130.6/30
      - name: GigabitEthernet0/4
        ip_address: 200.200.200.1/30
      - name: GigabitEthernet0/3
        ip_address: 200.200.200.5/30