---
- name: Gather device facts
  hosts: 10.10.10.150
  tasks:
    - name: gather facts
      junos_facts:         
      register: response
    - name: debug
      debug: 
        var: response
    - name: debug more
      debug:
        var: ansible_net_memfree_mb
    - name: debug even more
      debug:
        var: ansible_net_interfaces.me0