---
- name: Issue show commands
  hosts: sandbox
  connection: local
  tasks:
    - name: Show ip int brief
      ios_command:
        commands:
          - show ip int brief
        provider:
          host: ios-xe-mgmt-latest.cisco.com
          port: 8181    
          authorize: yes      
          username: root
          password: D_Vay!_10&
      register: if_data

    - name: Interfaces output
      debug:
        var: if_data['stdout_lines'][0]
